title: 'Al Bayan'
default_lang: Indonesia
author:
  name: 'Muhtadi Irfan'
  email: muhtadi.irfan@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  - 'JL KH Hasyim Ashari, Gang Kelurahan, No.B52, Kel. Neroktog, Kec. Pinang'
blog:
  route: /blog
